### ISSUE TITLE
Replace deprecated babel package

### ISSUE THREAD

**Issue by gvdp** [Bagaar/ember-graphql-mocking#187]
Warning when installing the package:

```
warning @bagaar/ember-graphql-mocking > ember-cli-babel > @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
```

Guess we should move to using https://www.npmjs.com/package/@babel/plugin-transform-private-methods

**Comment by bertdeblock** [comment]
I think we need to move this ticket to the `ember-cli-babel` repo.

**Comment by bertdeblock** [comment]
Closing, as I believe this should be addressed over in https://github.com/emberjs/ember-cli-babel.
